// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvnsytsxeirjnfxclwmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2bnN5dHN4ZWlyam5meGNsd212Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDkwMDMsImV4cCI6MjA2ODkyNTAwM30.RCrMCk3jamj-5Y8pRcHPrXul5EYl2eFOH9nNXp38FQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});